# Generated by Django 4.2.13 on 2024-05-30 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='operating_company',
            field=models.ForeignKey(blank=True, help_text='Operating company of the ship', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ships', related_query_name='ship', to='ships.operatingcompany', verbose_name='operating company'),
        ),
    ]
