# Generated by Django 4.2.13 on 2024-05-30 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0002_alter_ship_operating_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatingcompany',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operating_companies', related_query_name='operating_company', to='ships.contactperson', verbose_name='contact person'),
        ),
    ]
