name: Bug Report (Form)
description: File a bug report
title: '[Bug]: '
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Please search for existing issues before filing a new one. If you find a match, please add a comment to the existing issue instead of creating a new one.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: dropdown
    id: device
    attributes:
      label: Device
      description: What
      options:
        - Desktop
        - Smartphone
        - Tablet
        - Other
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      description: 'Which operating system do you use? Please provide the version as well if possible.'
      placeholder: 'macOS Big Sur 11.5.2'
    validations:
      required: true
  - type: textarea
    id: browser
    attributes:
      label: Browser
      description: 'Which browser do you use? Please provide the version as well if possible.'
      placeholder: 'Chrome Version 110.0.5481.100'
      value: |
        - Browser name:
        - Browser version:
      render: markdown
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: 'Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.'
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
  - type: textarea
    id: possible-solution
    attributes:
      label: Possible solution
      description: Add possible solutions here if any.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Add logs here if any.
      placeholder: 'Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.'
      render: shell
    validations:
      required: false
