# Generated by Django 4.2.13 on 2024-05-28 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vts', '0001_initial'),
        ('harbours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harbour',
            name='vts_centre',
            field=models.ForeignKey(blank=True, help_text='VTS Centre that is managing the harbour', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harbours', related_query_name='harbour', to='vts.vtscentre', verbose_name='VTS Centre'),
        ),
    ]
