# Generated by Django 4.2.13 on 2024-05-29 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harbours', '0002_harbour_vts_centre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harbour',
            name='location',
            field=models.ForeignKey(help_text='Location of the harbour', on_delete=django.db.models.deletion.CASCADE, related_name='harbours', to='harbours.location', verbose_name='location'),
        ),
    ]
