# Generated by Django 4.2.13 on 2024-05-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vtscentre',
            options={'verbose_name': 'VTS Centre', 'verbose_name_plural': 'VTS Centres'},
        ),
        migrations.AlterField(
            model_name='vtscentre',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address of the VTS Centre', max_length=255, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='vtscentre',
            name='name',
            field=models.CharField(help_text='Name of the VTS Centre', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='vtscentre',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number of the VTS Centre', max_length=20, verbose_name='phone'),
        ),
    ]
